### ISSUE TITLE
ISCSI EOF

### ISSUE THREAD

**Issue by ingvarrwvw** [LINBIT/linstor-gateway#15]
Hi.

After removing / adding new satellites, the gateway often stops working and gives the following error:

#linstor-gateway iscsi list
Error: Get "http://localhost:8080/api/v2/iscsi": EOF

curl http://localhost:8080/api/v2/iscsi
curl: (52) Empty reply from server

although at the moment there are iscsi-resources that are working and being used

linstor-gateway version 1.0.0

**Comment by ingvarrwvw** [comment]
And what to do with it? how to fix? and how to understand what he can not find?

**Comment by chrboe** [comment]
Can you outline what exactly you mean by "removing / adding new satellites"?

How many nodes did you have before, what LINSTOR commands did you run, and how many did you have afterwards?

**Comment by Samamy** [comment]
You most likely deleted a linstor node but did not delete it iscsi target associated for deleted node
