### ISSUE TITLE
Implement confirmation dialog when deleting

### ISSUE THREAD

**Issue by euh2** [LINBIT/linstor-gateway#23]
Simple but important feature: When doing i.e. `linstor-gateway nfs delete my-nfs-export`, there should be some confirmation. My first impression when testing this was that the **export** would be deleted, but **data** would remain. But everything is deleted. I want some guards protecting me from doing destructive actions!

**Comment by chrboe** [comment]
> Simple but important

Agree on both counts :wink: 

Thanks for the suggestion, I implemented it. Going through review now and should be in the next release.
