### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by leiw324** [LINBIT/linstor-gateway#26]
![image](https://github.com/LINBIT/linstor-gateway/assets/33790160/60fea57e-a5de-49f5-8aef-54d08ff4d183)

**Comment by chrboe** [comment]
Thanks for the hint, looks the CI action failed for that release.

I re-built the asset and uploaded it: https://github.com/LINBIT/linstor-gateway/releases/download/v1.3.0/linstor-gateway-linux-amd64

**Comment by leiw324** [comment]
Thanks!!
