### ISSUE TITLE
compatible with pacemaker 2.0?

### ISSUE THREAD

**Issue by meilihao** [LINBIT/linstor-gateway#4]
env:
- ubuntu 20.04
- pacemaker 2.0
- corosync 3.0
- linstor server 1.6.1
- drbdd 0.1.0

`linstor-iscsi start` does not work with no error.

linstor-iscsi:
![图片](https://user-images.githubusercontent.com/4382586/110065577-71144c00-7daa-11eb-8ba1-7e0d7d00557a.png)

crm configure:
![图片](https://user-images.githubusercontent.com/4382586/110065529-4e823300-7daa-11eb-84e0-3bc8a0f35e47.png)

**Comment by chrboe** [comment]
That crm config looks about right. What drbd/drbd-utils versions are you running? Maybe they don't support promotion scores yet. `drbdadm --version` should give you that information.

`crm status` would also be helpful.

**Comment by meilihao** [comment]
![图片](https://user-images.githubusercontent.com/4382586/110078453-b775a500-7dc2-11eb-9e0c-201e652a6289.png)

**Comment by chrboe** [comment]
Can you try again with the latest master? I'm reasonably certain this should be fixed with 0d257a998be276f3ce281fc69237320444f6ba9c.

Thanks for the report!

**Comment by meilihao** [comment]
@chrboe I updated and tried, but it does't work. crm resources is still stopped after `linstor-iscsi start`.

**Comment by chrboe** [comment]
Yes, that is expected. `linstor-gateway` only generates the CIB once (on the `linstor-iscsi create ...` command), and does not touch it again afterwards.

Maybe we need a `linstor-iscsi adjust ...` command which re-writes the CIB.

In the meantime, you'll either have to re-create your target or manually edit the constraints (`crm conf edit` and change all `inf` to `Mandatory` for the `order` constraints)

**Comment by meilihao** [comment]
@chrboe I created a new target and checked CIB, but the new linstor-iscsi didn't work.

![截图录屏_选择区域_20210318132944](https://user-images.githubusercontent.com/4382586/111577893-10473380-87ee-11eb-8865-a338a180a1c1.png)

**Comment by chrboe** [comment]
Can you post your `/var/log/pacemaker.log` somewhere? (e.g. pastebin)

**Comment by meilihao** [comment]
I'am sorry, my env is secure network, and no sending files to the public network.

**Comment by meilihao** [comment]
`tail -f /var/log/pacemaker/pacemaker.log` + `linstor-iscsi start`:
![截图录屏_选择区域_20210319114503](https://user-images.githubusercontent.com/4382586/111728969-f585c500-88a8-11eb-988a-bc84f9e33402.png)
![截图录屏_选择区域_20210319114526](https://user-images.githubusercontent.com/4382586/111728972-f74f8880-88a8-11eb-992c-fe00160aa7a5.png)
