### ISSUE TITLE
check-health not available in latest

### ISSUE THREAD

**Issue by bogdanro** [LINBIT/linstor-gateway#6]
Hi, 
linstor-gateway version 0.10.0

"linstor-gateway check-health" does nothing, just returns Usage

**Comment by chrboe** [comment]
Yes, the `check-health` command is not released in 0.10.0 yet. You currently have to build from git to get it.

Or you can stay tuned for just a little bit, the 0.11.0 release is right around the corner (coming either this week or early next week)
